WORKFLOW_JOB_APPLICATION_PREPARATION = "job_application_preparation"

RUN_STATUS_PENDING = "pending"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_COMPLETED = "completed"
RUN_STATUS_FAILED = "failed"
RUN_STATUS_NEED_MORE_INFO = "need_more_info"

STEP_STATUS_PENDING = "pending"
STEP_STATUS_RUNNING = "running"
STEP_STATUS_COMPLETED = "completed"
STEP_STATUS_FAILED = "failed"
STEP_STATUS_SKIPPED = "skipped"
STEP_STATUS_NEED_MORE_INFO = "need_more_info"

ERROR_AGENT_WORKFLOW_NOT_SUPPORTED = "agent_workflow_not_supported"
ERROR_MISSING_REQUIRED_SLOT = "missing_required_slot"
ERROR_RESUME_NOT_FOUND = "resume_not_found"
ERROR_RESUME_VERSION_NOT_FOUND = "resume_version_not_found"
ERROR_JOB_NOT_FOUND = "job_not_found"
ERROR_RESUME_VERSION_NOT_AVAILABLE = "resume_version_not_available"
ERROR_MATCH_REPORT_FAILED = "match_report_failed"
ERROR_RAG_SEARCH_FAILED = "rag_search_failed"
ERROR_AGENT_STEP_FAILED = "agent_step_failed"
